### ISSUE TITLE
Question about Figure 9

### ISSUE THREAD

**Issue by digbangbang** [cambrian-mllm/cambrian#11]
<img width="217" alt="image" src="https://github.com/cambrian-mllm/cambrian/assets/78746384/6398f39a-272d-4efa-b747-756a7d655da1">

Why the Filtered DVQA has 1550K data more than the DVQA 775K data, the latter I suppose is unfiltered?

Also the situation on the CLEVR(Filtered CLEVR 350K same as CLEVR 350K)

**Comment by tsb0601** [comment]
Hi, in Figure 9 and Cambrian-7M , we filtered out 1550K DVQA data and kept 775K DVQA data. The same applies to CLEVR. We used randomly sampling when we do filtering

**Comment by daa233** [comment]
Hi, @tsb0601  I wonder if the "filtered out 1550K DVQA data" are still in Cambrian7M's OCR part?

It seems 'yes' from the Figure 9:
![image](https://github.com/user-attachments/assets/01e34a79-1fff-4a68-9016-ee0f50f84f12)
