### ISSUE TITLE
Dataset License

### ISSUE THREAD

**Issue by JetGang** [cambrian-mllm/cambrian#2]
Hi, Nice work, and thanks for sharing! May I ask what's the license for the dataset Cambrian-10M and Cambrian-Alignment? Thanks!

**Comment by ellisbrown** [comment]
Thanks @JetGang! We have selected the Apache-2 license for all code, models, and datasets.

You can see more details here https://github.com/cambrian-mllm/cambrian?tab=readme-ov-file#license

**Comment by JetGang** [comment]
Thank you for the confirmation.
