### ISSUE TITLE
Question About Table 4

### ISSUE THREAD

**Issue by homiec** [cambrian-mllm/cambrian#23]
Thank you for your great work. 

Regarding the experiments in Table 4, I would like to ask if there are any direct comparisons to the experimental results of LLaVA (Vicuna-1.5-7B base LLM)? I'm curious about the experimental results of SVA compared with a single vision encoder?

**Comment by penghao-wu** [comment]
The results in Table 4 can be directly compared with Table 12 with single vision encoder.

**Comment by homiec** [comment]
Thanks
