### ISSUE TITLE
High resolution images 

### ISSUE THREAD

**Issue by Shade5** [cambrian-mllm/cambrian#26]
The default `inference.py` resizes images to 384. What's the correct way to use higher resolution images?

**Comment by penghao-wu** [comment]
The image will be processed by different image processors for different vision towers. For ConvNext, the image is resized to 1024.

**Comment by Mac0q** [comment]
@Shade5 Sorry to bother you. I would like to ask how to enable ConvNext vision tower during the inference stage, if only using the pre-trained model. I have simply tried replacing mm_vision_tower_aux_list in config.json, but it doesn't seem to work.
