### ISSUE TITLE
Internet Data Engine publish

### ISSUE THREAD

**Issue by HyunHo99** [cambrian-mllm/cambrian#3]
Thank you for releasing this cool research as open source!
I am very impressed with the Internet Data Engine used to collect data and would like to try it myself.
Are there any plans to release the code?

**Comment by tsb0601** [comment]
Hi, thank you for interests in our work! We plan to release the data engine within 1 week. We are currently cleaning that part of the code. I will update you and close the issue when we release it

**Comment by ellisbrown** [comment]
@HyunHo99 the data engine was just merged into the codebase thanks to @Charithaakula !

you can see more info in the [dataengine/](https://github.com/cambrian-mllm/cambrian/tree/main/dataengine) subdir
