### ISSUE TITLE
nyu-visionx/cambrian-phi3-3b benchmarks

### ISSUE THREAD

**Issue by danieltudosiu** [cambrian-mllm/cambrian#31]
Thank you for the amazing work you did with Cambrian-1.

I observed that on your HF you have also released [a Phi3 model](https://huggingface.co/nyu-visionx/cambrian-phi3-3b) but I could not find it on your website nor in your paper. 

Could be ever so kind as in to share some of your internal benchmarks of the model, as I assume since you released it you also benchmarked it internally but decided not to write about it in the paper.

Thank you very much in advance!

**Comment by tsb0601** [comment]
Hi, we actually finished training the model after releasing the paper. We just done the benchmark evaluation and and we will add it later today

**Comment by danieltudosiu** [comment]
@tsb0601 thanks a lot for the update. Looking forward to the results.

**Comment by tsb0601** [comment]
@danieltudosiu Hi, we updated phi-3 results in the README here and full results in the Cambrian-1-3B model card: https://huggingface.co/nyu-visionx/cambrian-phi3-3b

Thanks  you for interest in our work!
