### ISSUE TITLE
Multi image inference

### ISSUE THREAD

**Issue by Beakboomboom** [cambrian-mllm/cambrian#34]
I use two special tokens <image> and input 2 images, but got error in cambrian_llama.py Line 228

Because final_vision_feature_size length is 2, but hidden state shape 0 is 1.

I wonder how to organize multiple images for inference?

![20240704-161830](https://github.com/cambrian-mllm/cambrian/assets/12118547/77b3c8ff-c51c-4a50-baae-ea2f56b1fd56)

**Comment by yucy207** [comment]
same problem, did you solve this?

**Comment by yucy207** [comment]
seems only support single image input
https://github.com/cambrian-mllm/cambrian/issues/4
