### ISSUE TITLE
Question about data_engine part dataset

### ISSUE THREAD

**Issue by vikyzeng** [cambrian-mllm/cambrian#38]
I found that the data_engine data did not match the pictures very seriously. Is this a problem with the decompression, or is the question and answer quality itself very poor?

**Comment by Charithaakula** [comment]
The actual dataset would depend on the topic and the quality of the source material, such as wiki pages. The aim of our work was to showcase the potential of this framework. By experimenting with more refined prompts and higher-quality resources, we can get higher quality output. Regardless, this approach offers scientific instruction tuning data on the language side, with image coherent to the topic.
