### ISSUE TITLE
Support Of Multiple Images Infering

### ISSUE THREAD

**Issue by caichuang0415** [cambrian-mllm/cambrian#4]
Thanks for your great work, and I've tried it and I am surprised by its good performance.
But the inference script you provide now only supports one image a time inferring, I hope you upgrade it so that it can go multiple images inferring.
Besides, it would be better if it supports in-context dialog

**Comment by ellisbrown** [comment]
Hi @caichuang0415 thanks for your interest in our work!

Unfortunately, Cambrian-1 only supports single-image inference. Multiple image support would require developing a separate model and new training data, and so we do not have plans to do this immediately. This is something that we may investigate down the road though!
