### ISSUE TITLE
When using inference.py I meet this package problem.Could this be related to changing the torch version to 2.0.1 for CUDA 11.7?

### ISSUE THREAD

**Issue by Chengnotwang** [cambrian-mllm/cambrian#41]
![image](https://github.com/cambrian-mllm/cambrian/assets/109078083/43ef943c-24aa-4ee4-bd88-5a5a6f8770e5)

**Comment by penghao-wu** [comment]
It should be related to some package version issues. What it the version of your `transformers` and `huggingface_hub`?

**Comment by Chengnotwang** [comment]
> It should be related to some package version issues. What it the version of your `transformers` and `huggingface_hub`?

The vresion of transformers is 4.37.0 and huggingface_hub is 0.23.4

**Comment by penghao-wu** [comment]
Can you try this https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949 ?

**Comment by Chengnotwang** [comment]
> Can you try this [huggingface/transformers#15062 (comment)](https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949) ?

Thanks，I will try it

**Comment by Chengnotwang** [comment]
> Can you try this [huggingface/transformers#15062 (comment)](https://github.com/huggingface/transformers/issues/15062#issuecomment-1821349949) ?

Thank you，It works and no longer reports this error!
