### ISSUE TITLE
Cambrian-phi3-3b

### ISSUE THREAD

**Issue by BrenchCC** [cambrian-mllm/cambrian#47]
What kind of dataset ratio was adopted in the latest release of Cambrian-phi3-3b

**Comment by tsb0601** [comment]
Hi, Cambrian-phi3-3b used the Cambrian-7M (https://huggingface.co/datasets/nyu-visionx/Cambrian-10M/resolve/main/jsons/Cambrian7M_withsystemprompt.jsonl), same as the Cambrian-8b, 13b and 33b models
