### ISSUE TITLE
where is the sva projector? 

### ISSUE THREAD

**Issue by ZhuGeKongKong** [cambrian-mllm/cambrian#53]
I cannot find the sva projector in the cambrian/model/multimodal_projector/ field.

**Comment by penghao-wu** [comment]
The sva projector is implemented at `cambrian/model/vision_sampler.py` in and initialized at https://github.com/cambrian-mllm/cambrian/blob/07bc9f70fb2eaa6615c36c15765c13993c66ab44/cambrian/model/cambrian_arch.py#L60 and https://github.com/cambrian-mllm/cambrian/blob/07bc9f70fb2eaa6615c36c15765c13993c66ab44/cambrian/model/cambrian_arch.py#L68.
