### ISSUE TITLE
There is an error in Table 3, Vision Backbone in lines 3 and 6 are both "SigLIP+DINOv2+ConvNext"

### ISSUE THREAD

**Issue by dingangui** [cambrian-mllm/cambrian#56]

**Comment by ellisbrown** [comment]
thanks for reporting this! I just double-checked, and that run used a [ConvNeXt-L](https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup) not and XXL. We will fix this in the next revision!
