### ISSUE TITLE
[BUG] Unable to download model weights from Huggingface

### ISSUE THREAD

**Issue by peiqi-liu** [cambrian-mllm/cambrian#59]
Hello,

I attempted to load Cambrian model weights from huggingface. 

I used following commands to do so:
`from transformers import AutoModelForCausalLM`
`model = AutoModelForCausalLM.from_pretrained("nyu-visionx/cambrian-8b")`

However, I received error message saying:
`ValueError: The checkpoint you are trying to load has model type cambrian_llama but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.`

I tried to run the codes with different `transformers` version but I always had this error message.

**Comment by penghao-wu** [comment]
Our model is not integrated into transformers. You have to install our repo to load and use our models (see `inference.py`).

**Comment by peiqi-liu** [comment]
Got it. Thanks.
