### ISSUE TITLE
support Chinese?

### ISSUE THREAD

**Issue by lorashen** [cambrian-mllm/cambrian#6]
does this model support Chinese language?

**Comment by tsb0601** [comment]
Hi, 

Thanks for interest in our work! The support for Chinese language comes with native multilingual ability from language backbones (LLaMA, Vicuna, Yi). However, we did not fine-tune additional Chinese datasets for more advanced Chinese ability. Based on our personal experiences, the model understands and can respond in Chinese. Feel free to try it and share your experience with us. We are also hoping to support more advanced multilingual in future releases if possible.
