### ISSUE TITLE
For experiments in section 3.3, did you use the cambrian model architecture or llava?

### ISSUE THREAD

**Issue by xrc10** [cambrian-mllm/cambrian#61]
![image](https://github.com/user-attachments/assets/cd821f18-24b8-4837-bf07-be6d50c04839)

Thanks for sharing your great work! Just the question on the title. I am asking because I found unfreezing vision tower is hardly beneficial with the vanilla llava architecture, so I was wondering if you draw your conclusion on your novel architecture as shown in the figure.

**Comment by ellisbrown** [comment]
we use the llava architecture for these experiments.

I recall unfreezing being a bit sensitive to the vision-model learning rate---took a bit of hparam tuning to get a good setting. you can see our hparams in table 19

![image](https://github.com/user-attachments/assets/421ce413-d20e-4b3b-890b-0951e262d3f5)

**Comment by xrc10** [comment]
> we use the llava architecture for these experiments.
> 
> I recall unfreezing being a bit sensitive to the vision-model learning rate---took a bit of hparam tuning to get a good setting. you can see our hparams in table 19
> 
> ![image](https://private-user-images.githubusercontent.com/5157986/352240221-421ce413-d20e-4b3b-890b-0951e262d3f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTU4MTQsIm5iZiI6MTcyMTk1NTUxNCwicGF0aCI6Ii81MTU3OTg2LzM1MjI0MDIyMS00MjFjZTQxMy1kMjBlLTRiM2ItODkwYi0wOTUxZTI2MmQzZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMDA1ODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJkMWZiNDQ0ZDcxOTRkMTU0Y2ZjOTczOWQ5YzJkYTZmMjg2OTRhN2RlMjRhY2JhYTA3YjU4OTViZjVkODY3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N57rari6Mfu1JwkWWBQ95_52T852_ZHtc6pS-9QXuAw)

Thank you for your reply! This is very helpful!
