### ISSUE TITLE
Evaluation with datasets that contains multiple images

### ISSUE THREAD

**Issue by Nyandwi** [cambrian-mllm/cambrian#66]
Hello, thanks for this amazing work!

This previous [issue](https://github.com/cambrian-mllm/cambrian/issues/4) mentions that Cambrian only support one-image input during inference. I was wondering how you do evaluations on datasets that have multiple images in one sample like MMMU.

CC: @ellisbrown

**Comment by ellisbrown** [comment]
thanks for your interest @Nyandwi!

We use only the subset of examples with single images on benchmarks like MMMU.

**Comment by Nyandwi** [comment]
Thank you @ellisbrown! That's very nice to know and appreciate your time :-)
