### ISSUE TITLE
Fail to Reproduce the Performance on MMVP.

### ISSUE THREAD

**Issue by Haochen-Wang409** [cambrian-mllm/cambrian#75]
Hi, it is reported in Table 8 that Cambrian-1-8b achieves 51.3 on MMVP.
However, I downloaded your official checkpoint and evaluated by myself, the performance is only 39.3.

I provided the answers inference by Cambrian-1-8b, and I used GPT-4o to grade the answers.
[cambrian-8b.json](https://github.com/user-attachments/files/16906229/cambrian-8b.json)

**Comment by WayneJin0918** [comment]
you can use eval in eval/eval/mmvp/mmvp_eval.py. This will be more stable and I reproduce it successfully

**Comment by Haochen-Wang409** [comment]
Thanks for the reply! I have successfully reproduced the results.
