### ISSUE TITLE
CV-Bench Evaluation

### ISSUE THREAD

**Issue by nku-zhichengzhang** [cambrian-mllm/cambrian#81]
Congrats to the Cambrian team on your acceptance to NeurIPS! This is a significant achievement, and it's a testament to the hard work and innovation you've put into the project.

### Issue Description

While exploring the repository, I noticed that there seems to be no inference and evaluation codes for cv-bench in the `eval/eval` folder.

### Questions

1. Is the evaluation code for cv-bench located elsewhere in the repository?
2. If not, are there plans to add this code to the `eval/eval` folder or another appropriate location?
3. Is there any specific reason for not including the cv-bench evaluation code at this time?

**Comment by Jike338** [comment]
same ask here :))

**Comment by WayneJin0918** [comment]
CVbench2D is the average of COCO and ADE in eval. CVbench3D is the Omni in eval. You can find it directly.

**Comment by WayneJin0918** [comment]
**https://github.com/cambrian-mllm/cambrian/tree/main/eval/eval/ade 
https://github.com/cambrian-mllm/cambrian/tree/main/eval/eval/coco 
https://github.com/cambrian-mllm/cambrian/tree/main/eval/eval/omni**
 for details.

**Comment by nku-zhichengzhang** [comment]
Thx for details~

**Comment by mashijie1028** [comment]
@WayneJin0918 
Hi, do you know how to download the Omni data?
```
parser.add_argument("--images_path", type=str, default="/scratch/eb3174/datasets/vision-benchmark/")
parser.add_argument("--prompt_path", type=str, default="/scratch/eb3174/datasets/vision-benchmark/3D_VQA.json")
```

Thanks!

**Comment by mashijie1028** [comment]
Oh! I figured it out! Just download the full CV-Bench dataset from https://huggingface.co/datasets/nyu-visionx/CV-Bench and filter out 2D data like:
```
if line["type"] == '2D':
    continue
```
